general:
  # Possible values: B_1_8_1, B_1_7_3, B_1_6_6, B_1_9
  beta_version: B_1_7_3
  # MOTD which will be displayed on server ping list
  # if 'beta_1_8_ping_passthrough' is not enabled
  motd: '&9Release2Beta server'
  max_players: 10
connection:
  # Beta server address
  remote_address: localhost
  remote_port: 25567
  # Address to connect from modern Minecraft client
  bind_address: localhost
  bind_port: 25565
  global_connection_throttle: 3000
  # Beta server have to be offline first
  online_mode: false
  # Compression threshold (0 = all packets will be compressed)
  compression_threshold: 256
misc:
  resource_pack_url: ''
  resource_pack_hash: ''
  # Player nicknames autocompleting
  tab_complete: true
  skin_fix: false
  disable_sprinting: true
  # Displays MOTD from beta server
  beta_1_8_ping_passthrough: false
messages:
  # Ignored if running on bukkit
  server_full_message: Server is full
  connection_throttle_kick_message: '&cConnection Throttled! Try again later'
  no_spam_message: '&cyou''re sending messages too quickly'
  spam_protection: true
  log_pings: true
experimental:
  # Do not enable this unless you know what you're doing
  enable_chunk_updates: false
metrics:
  enable_metrics: true
  unique_id: default
debug:
  suppressMappingsErrors: false